version: '2'
services:
  postgres:
      image: postgres:9.6
      container_name: postgres-docker
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
      ports:
          - 5432:5432
      volumes:
          - ./examples/datavault2-bigdata-example/setup/100_restore.sql:/docker-entrypoint-initdb.d/100_restore.sql
          - ./examples/datavault2-bigdata-example/setup/200_users.sql:/docker-entrypoint-initdb.d/200_users.sql
          - ./examples/datavault2-bigdata-example/setup/data:/docker-entrypoint-initdb.d/data
  hive:
      image: cloudera/quickstart:latest
      container_name: hive-docker
      restart: always
      depends_on:
          - postgres
      ports:
          - 8888:8888
          - 10000:10000
          - 7180:7180
          - 8020:8020
      volumes:
          - ./examples/datavault2-bigdata-example/hive-site.xml:/etc/hive/conf.dist/hive-site.xml
          - /tmp/datavault2-bigdata-example:/external
      hostname: quickstart.cloudera
      privileged: true
      tty: true
      command: /usr/bin/docker-quickstart
  webserver:
      image: gtoonstra/docker-airflow:1.9.0
      container_name: airflow
      restart: always
      depends_on:
          - postgres
          - hive
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
          - INSTALL_HIVE=y
      volumes:
          - ./examples/datavault2-bigdata-example/dags:/usr/local/airflow/dags
          - ./examples/datavault2-bigdata-example/dataflow:/usr/local/airflow/dataflow
          - ./examples/datavault2-bigdata-example/sql:/usr/local/airflow/sql
          - ./examples/datavault2-bigdata-example/core-site.xml:/core-site.xml
          - ./examples/datavault2-bigdata-example/hdfs-site.xml:/hdfs-site.xml
          - ./examples/datavault2-bigdata-example/mapred-site.xml:/mapred-site.xml
          - /tmp/datavault2-bigdata-example:/tmp/datavault2-bigdata-example
          - ./examples/datavault2-bigdata-example/requirements.txt:/requirements.txt
      ports:
          - 8080:8080
      command: webserver